"""initial schema

Creates every table, constraint and index from SPEC-1
(docs/specs/SPEC-1-database-schema.md, Section 2), including SPEC-1
Amendment 1 (the composite foreign key that enforces FR-7).

Revision ID: 0001
Revises:
Create Date: 2026-10-06

The DDL below is written out explicitly (not autogenerated) so it can be
reviewed against SPEC-1 line by line, and so it stays a frozen snapshot of the
schema at this point in time — it must never import src/db/tables.py, whose
contents evolve. Constraint and index names match src/db/tables.py exactly
(which itself follows SPEC-1's explicit names plus the MetaData naming
convention), so the database and the SQLAlchemy definitions agree.

The literal string values in the CHECK constraints and server defaults below
are an intentional snapshot of the shared vocabulary in src/core/enums.py
(roles, statuses, seat types). They are copied, not imported: editing them
here would silently change the meaning of an already-applied migration.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create all tables, constraints and indexes in dependency order.

    Parents are created before the tables that reference them: users, genres,
    movies, movie_genres, screens, seats, showtimes, reservations, then
    seat_reservations. Indexes are created immediately after the table they
    belong to.
    """
    # --- users (SPEC-1 2.1) ------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False, server_default=sa.text("'user'")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.CheckConstraint("role IN ('user', 'admin')", name="users_role_check"),
    )
    # FR-1: case-insensitive email uniqueness via a functional unique index.
    op.create_index(
        "idx_users_email_lower",
        "users",
        [sa.text("lower(email)")],
        unique=True,
    )

    # --- genres (SPEC-1 2.2) ----------------------------------------------
    op.create_table(
        "genres",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_genres"),
        sa.UniqueConstraint("name", name="uq_genres_name"),
    )

    # --- movies (SPEC-1 2.3) ----------------------------------------------
    op.create_table(
        "movies",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "description", sa.Text(), nullable=False, server_default=sa.text("''")
        ),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_movies"),
    )
    op.create_index("idx_movies_title", "movies", ["title"])

    # --- movie_genres (many-to-many, SPEC-1 2.4) --------------------------
    op.create_table(
        "movie_genres",
        sa.Column("movie_id", sa.BigInteger(), nullable=False),
        sa.Column("genre_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("movie_id", "genre_id", name="pk_movie_genres"),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
            name="fk_movie_genres_movie_id_movies",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
            name="fk_movie_genres_genre_id_genres",
            ondelete="RESTRICT",
        ),
    )

    # --- screens (SPEC-1 2.5) ---------------------------------------------
    op.create_table(
        "screens",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("rows", sa.SmallInteger(), nullable=False),
        sa.Column("seats_per_row", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_screens"),
        sa.UniqueConstraint("name", name="uq_screens_name"),
        sa.CheckConstraint("rows > 0", name="screens_rows_positive"),
        sa.CheckConstraint("seats_per_row > 0", name="screens_seats_per_row_positive"),
    )

    # --- seats (SPEC-1 2.6) -----------------------------------------------
    op.create_table(
        "seats",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("screen_id", sa.BigInteger(), nullable=False),
        sa.Column("row_label", sa.Text(), nullable=False),
        sa.Column("seat_number", sa.SmallInteger(), nullable=False),
        sa.Column(
            "seat_type",
            sa.Text(),
            nullable=False,
            server_default=sa.text("'standard'"),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_seats"),
        sa.ForeignKeyConstraint(
            ["screen_id"],
            ["screens.id"],
            name="fk_seats_screen_id_screens",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "seat_type IN ('standard', 'accessible')", name="seats_type_check"
        ),
        sa.UniqueConstraint(
            "screen_id", "row_label", "seat_number", name="seats_unique_position"
        ),
    )

    # --- showtimes (SPEC-1 2.7) -------------------------------------------
    op.create_table(
        "showtimes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("movie_id", sa.BigInteger(), nullable=False),
        sa.Column("screen_id", sa.BigInteger(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_showtimes"),
        # FR-4: deleting a movie/screen with showtimes is blocked (RESTRICT).
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
            name="fk_showtimes_movie_id_movies",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["screen_id"],
            ["screens.id"],
            name="fk_showtimes_screen_id_screens",
            ondelete="RESTRICT",
        ),
        # FR-5: price must be strictly positive.
        sa.CheckConstraint("price_cents > 0", name="showtimes_price_positive"),
    )
    op.create_index("idx_showtimes_movie_date", "showtimes", ["movie_id", "starts_at"])
    op.create_index("idx_showtimes_date", "showtimes", ["starts_at"])

    # --- reservations (SPEC-1 2.8) ----------------------------------------
    op.create_table(
        "reservations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("showtime_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status", sa.Text(), nullable=False, server_default=sa.text("'held'")
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_reservations"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_reservations_user_id_users",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["showtime_id"],
            ["showtimes.id"],
            name="fk_reservations_showtime_id_showtimes",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "status IN ('held', 'confirmed', 'cancelled', 'expired')",
            name="reservations_status_check",
        ),
        # FR-7 (Amendment 1): redundant with the primary key on purpose — it
        # exists only as the target of the composite FK on seat_reservations.
        sa.UniqueConstraint(
            "id", "showtime_id", name="reservations_id_showtime_unique"
        ),
    )
    op.create_index(
        "idx_reservations_user",
        "reservations",
        ["user_id", sa.text("created_at DESC")],
    )
    op.create_index(
        "idx_reservations_showtime", "reservations", ["showtime_id", "status"]
    )

    # --- seat_reservations (SPEC-1 2.9) -----------------------------------
    op.create_table(
        "seat_reservations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("reservation_id", sa.BigInteger(), nullable=False),
        sa.Column("showtime_id", sa.BigInteger(), nullable=False),
        sa.Column("seat_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status", sa.Text(), nullable=False, server_default=sa.text("'held'")
        ),
        sa.PrimaryKeyConstraint("id", name="pk_seat_reservations"),
        # FR-6 / FR-7 (Amendment 1): the composite FK keeps the denormalized
        # showtime_id honest and cascades when the parent reservation is
        # deleted. It replaces the former single-column reservation_id FK.
        sa.ForeignKeyConstraint(
            ["reservation_id", "showtime_id"],
            ["reservations.id", "reservations.showtime_id"],
            name="seat_reservations_reservation_showtime_fk",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["showtime_id"],
            ["showtimes.id"],
            name="fk_seat_reservations_showtime_id_showtimes",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["seat_id"],
            ["seats.id"],
            name="fk_seat_reservations_seat_id_seats",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "status IN ('held', 'confirmed', 'cancelled', 'expired')",
            name="seat_reservations_status_check",
        ),
    )
    # FR-2 / FR-3: at most one ACTIVE row per (showtime_id, seat_id); terminal
    # rows (cancelled/expired) are excluded by the WHERE clause so they never
    # block a new hold.
    op.create_index(
        "idx_seat_reservations_active_unique",
        "seat_reservations",
        ["showtime_id", "seat_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('held', 'confirmed')"),
    )
    op.create_index(
        "idx_seat_reservations_reservation",
        "seat_reservations",
        ["reservation_id"],
    )


def downgrade() -> None:
    """Drop everything upgrade() created, in reverse dependency order.

    Indexes are dropped explicitly (rather than relying on the table drop) so
    the downgrade mirrors upgrade() one statement at a time, then each table
    is dropped children-first so no foreign key is left dangling.
    """
    # seat_reservations (no dependents)
    op.drop_index("idx_seat_reservations_reservation", table_name="seat_reservations")
    op.drop_index("idx_seat_reservations_active_unique", table_name="seat_reservations")
    op.drop_table("seat_reservations")

    # reservations
    op.drop_index("idx_reservations_showtime", table_name="reservations")
    op.drop_index("idx_reservations_user", table_name="reservations")
    op.drop_table("reservations")

    # showtimes
    op.drop_index("idx_showtimes_date", table_name="showtimes")
    op.drop_index("idx_showtimes_movie_date", table_name="showtimes")
    op.drop_table("showtimes")

    # seats, screens
    op.drop_table("seats")
    op.drop_table("screens")

    # movie_genres (join table)
    op.drop_table("movie_genres")

    # movies
    op.drop_index("idx_movies_title", table_name="movies")
    op.drop_table("movies")

    # genres
    op.drop_table("genres")

    # users
    op.drop_index("idx_users_email_lower", table_name="users")
    op.drop_table("users")
